- become: true
  block:
  - name: Install packages
    apt:
      name: "{{ apt_packages }}"

  - name: Upgrade all packages
    apt:
      upgrade: true
      autoclean: true
      autoremove: true
      update_cache: true
