- name: Get Windows username
  shell: /mnt/c/Windows/System32/cmd.exe /c echo %USERNAME% | sed --expression='s/\r//g'
  register: win_user
  changed_when: false
  check_mode: false

- name: Symlink folders
  file:
    state: link
    src: "{{item.value}}"
    dest: "~/{{item.key}}"
    force: true
  with_dict:
    wincode: "/mnt/c/code"
    desktop: "/mnt/c/Users/{{win_user.stdout}}/Desktop"
    downloads: "/mnt/c/Users/{{win_user.stdout}}/Downloads"
    temp: "/mnt/c/temp"

- name: Add wsl.conf
  become: true
  copy:
    src: "/home/{{ lookup('env','USER') }}/.devbox/wsl/wsl.conf"
    dest: "/etc/wsl.conf"
    remote_src: true

# From https://github.com/microsoft/WSL/issues/4737
# Disable X11 and pulseaudio checks for startup speed
- name: Custom wsl-integration.sh
  become: true
  copy:
    src: "/home/{{ lookup('env','USER') }}/.devbox/wsl/wsl-integration.sh"
    dest: "/etc/profile.d/wsl-integration.sh"
    remote_src: true

- name: Link WSL dotfiles
  file:
    state: link
    src: '{{ item }}'
    dest: '~/{{ item | basename }}'
    force: true
  with_fileglob:
    - '~/.devbox/dotfiles/wsl/.*'