- become: true
  block:
  - name: Add Microsoft key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add Azure CLI to sources list
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"

  - name: Install Azure CLI
    apt:
      name: 
      - apt-transport-https
      - azure-cli