- name: Install Python build tools
  become: true
  apt:
    name:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - python-openssl
    - git

- name: Check for pyenv
  stat:
    path: ~/.pyenv
  register: pyenv

- name: Install pyenv
  when: not pyenv.stat.exists
  shell: curl https://pyenv.run | bash
