- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: macosx.yml
  when: ansible_distribution == 'MacOSX'

- name: Install {{ python_version }} via pyenv
  shell: |
    export PATH="/home/{{ ansible_user_id }}/.pyenv/bin:$PATH"  # for Linux
    pyenv update
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}
