- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: macosx.yml
  when: ansible_os_family == 'MacOSX'

- name: Check for pyenv
  stat:
    path: ~/.pyenv
  register: pyenv

- name: Install pyenv
  when: not pyenv.stat.exists
  shell: curl https://pyenv.run | bash

- name: Install {{ python_version }} via pyenv
  shell: |
    export PATH="/home/{{ ansible_user_id }}/.pyenv/bin:$PATH"
    pyenv update
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}

- name: Install ansible
  shell: |
    eval "$(pyenv init - bash --no-rehash)"
    python -m pip install ansible --user
