- name: Install nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: ~/.nvm
    version: v0.34.0

- name: Install latest node via nvm
  shell: |
    export NVM_DIR="$HOME/.nvm"
    . ~/.nvm/nvm.sh
    nvm install --lts
    nvm alias default node

    BIN_DIR=$(dirname $(nvm which current))
    echo "export PATH=\"$BIN_DIR:$PATH\"" > ~/.devbox/dotfiles/includes/__node.sh
