- name: Install tools to untar files
  homebrew:
    name: gnu-tar

##########
# dapr
##########
- name: Install dapr
  become: true
  when: current_dapr_version is failed or current_dapr_version.stdout != dapr_version
  block:
  - name: Create staging directory for dapr
    file:
      path: /usr/local/src/dapr
      state: directory

  - name: Extract dapr
    unarchive:
      src: "https://github.com/dapr/cli/releases/download/{{ dapr_version }}/dapr_darwin_amd64.tar.gz"
      dest: /usr/local/src/dapr
      remote_src: true
      force: true

  - name: Copy dapr to /usr/local/bin
    copy:
      src: /usr/local/src/dapr/dapr
      dest: /usr/local/bin/dapr
      remote_src: true
      mode: 0755
      force: true

##########
# porter
##########
- name: Install porter
  when: current_porter_version is failed or current_porter_version.stdout != porter_version
  shell: |
    export PORTER_PERMALINK={{ porter_version }}
    curl -L https://cdn.porter.sh/latest/install-mac.sh | bash
