- become: true
  block:
  - name: Add Microsoft key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add .NET to sources list
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_distribution_release }}-prod {{ ansible_distribution_release }} main"

  - name: Install .NET SDK
    apt:
      name: 
      - apt-transport-https
      - dotnet-sdk-2.2
