- name: Add Docker key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker to sources list
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} edge"

- name: Install Docker
  become: true
  apt:
    name: docker-ce

- name: Add user to Docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Install docker-compose
  shell: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
